smtp_on: true
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: selenium_training
smtp_password: DrupalCon2016
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: U7C23Wy4M4Eq8X8ExjU4n3yq7PtfU1S-jebw2hikU5g
